version: 2

project_name: skills

builds:
  - skip: true

release:
  name_template: "{{.Tag}}"

changelog:
  use: github
  groups:
    - title: Features
      regexp: ^.*?feat(\(.+\))??!?:.+$
      order: 0
    - title: "Bug fixes"
      regexp: ^.*?fix(\(.+\))??!?:.+$
      order: 1
    - title: "Performance"
      regexp: ^.*?perf(\(.+\))??!?:.+$
      order: 2
    - title: "Enhancements"
      regexp: ^.*?chore(\(.+\))??!?:.+$
      order: 3
    - title: "Refactor"
      regexp: ^.*?refactor(\(.+\))??!?:.+$
      order: 4
    - title: "Style"
      regexp: ^.*?style(\(.+\))??!?:.+$
      order: 5
    - title: "Tests"
      regexp: ^.*?test(\(.+\))??!?:.+$
      order: 6
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 7
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 8
    - title: Others
      order: 999
